# Generated by Django 3.2.6 on 2021-08-31 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mineral', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=200)),
                ('properties', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=2000)),
                ('img_path', models.CharField(max_length=100, unique=True)),
                ('acquire_date', models.DateTimeField()),
                ('checked_out', models.BooleanField()),
                ('stone_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sarasstones.color')),
                ('stone_cut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sarasstones.cut')),
                ('stone_mineral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sarasstones.mineral')),
            ],
        ),
    ]
