# Generated by Django 3.2.6 on 2021-08-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarasstones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='cut',
            name='cut',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='mineral',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
