# Generated by Django 3.2.6 on 2021-08-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarasstones', '0003_auto_20210831_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='brief',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='properties',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='img_path',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='notes',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
