# Generated by Django 3.2.6 on 2021-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarasstones', '0006_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='brief',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='properties',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
