# Generated by Django 3.2.6 on 2021-08-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarasstones', '0007_auto_20210831_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stone',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stone',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
