# Generated by Django 3.2.6 on 2021-08-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarasstones', '0008_auto_20210831_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='stone',
            name='current_borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sarasstones.user'),
        ),
    ]
