# Generated by Django 3.2.6 on 2021-08-31 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sarasstones', '0009_stone_current_borrower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stone',
            name='img_path',
        ),
        migrations.CreateModel(
            name='ImagePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('stone_image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sarasstones.stone')),
            ],
        ),
        migrations.AddField(
            model_name='stone',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sarasstones.imagepath'),
        ),
    ]
